### ISSUE TITLE
Failing tests @hack.p6c.org

### ISSUE THREAD

**Issue by samcv** [gfldex/perl6-meta6-bin#14]
See log here: http://hack.p6c.org/~samcv/ecosystem-tests/2017-04-28_21.52/META6::bin:ver('0.8.5'):auth('github:gfldex').log

Logs for other modules failing during that run are here:
 https://gist.github.com/samcv/5339208c44a4d65f5165508e02dd0cee

```
# Failed test 'can load META6::bin'
# at t/010-load.t line 6
# No such method 'slurp' for invocant of type 'Int'
```
Putting @hack.p6c.org in the title so I can (potentially) automate the tracking of these issues.

**Comment by gfldex** [comment]
fixed with https://github.com/gfldex/perl6-git-config/commit/78a6ce9e19986ef61928d7b21916f886ca45eadb
