### ISSUE TITLE
add .gitignore file

### ISSUE THREAD

**Issue by melezhik** [gfldex/perl6-meta6-bin#2]
It'd be nice to add .gitingnore file, my way is:

```
$ cat  .gitignore 
lib/.precomp
```

**Comment by gfldex** [comment]
Already planned. I just need to find the time to steal `.gitignores` from many modules to build a good avg.

**Comment by melezhik** [comment]
Yeah, sure. "lib/.precomp" is my minimal preset )))

**Comment by jonathanstowe** [comment]
Yeah most of mine only have .precomp  (don't even need the lib) I add specific ones when there might be some C compilation involved for instance.

**Comment by gfldex** [comment]
fixed with d338fb345aa17cf44f3e175bd55ed29bd262d9e7
