### ISSUE TITLE
Failed to parse .gitconfig

### ISSUE THREAD

**Issue by samcv** [gfldex/perl6-meta6-bin#7]
```
===SORRY!===
Failed to parse „~/.gitconfig“.
```
Here is my .gitconfig: https://github.com/samcv/dot-files/blob/d1335a4e31df20e323277890d65a70a673eaa262/.gitconfig

**Comment by gfldex** [comment]
fixed in Git::Config:ver('0.1.2'):auth('github:gfldex')
